### ISSUE TITLE
Ordering Wastebox for recycling 3D printing material

### ISSUE THREAD

**Issue by beniroquai** [openUC2/UC2-GIT#45]
Long-time ago we were thinking about recycling 3D printing material. One service is this [one](https://zerowasteboxes.terracycle.com/products/3d-printing-materials-zero-waste-box?variant=1264347272&utm_source=www.terracycle.com&utm_medium=main_button&utm_campaign=ZeroWasteBox). 
I think that's fairly expensive. Maybe we can find some local alternative? 

Any ideas @RainerHeintzmann @b286?

**Comment by b286** [comment]
I'm totally up for recycling the materials, the waste makes me sad. If we just use Prusament, maybe we could contact Prusa and ask if they would accept the material back? They produce everything themselves, they could have a way of dealing with this. I don't know :D

**Comment by beniroquai** [comment]
Are you keen on doing that? :)

**Comment by b286** [comment]
I can certainly try :D

**Comment by beniroquai** [comment]
We have a plastic grinder. We will recycle stuff now with the new IM machine
