### ISSUE TITLE
useetoo.org may be hosting malware

### ISSUE THREAD

**Issue by recri** [openUC2/UC2-GIT#48]
My adblocker refused to open useetoo.org because of the trackers and known malware distributors being accessed in by the website.  This is the first time I recall this happening.  I allowed the trackers temporarily and landed at a "prize" page for my number of google searches.  Has your web site been hacked?

**Comment by RainerHeintzmann** [comment]
Dear Roger,
Thanks for telling us. I think you are right.
It looks like it was hacked. We will try to fix this asap.
Thanks,
  Rainer

**Comment by beniroquai** [comment]
Thanks for the comment! I was already facing that on Monday. @renerichter is on it. Let's hope for the best!

**Comment by beniroquai** [comment]
we have a new webpage. Coming soon
