### ISSUE TITLE
Print Mechanical Z-stage without support or add supports?

### ISSUE THREAD

**Issue by dakoner** [openUC2/UC2-GIT#49]
This page:
https://github.com/bionanoimaging/UC2-GIT/tree/master/CAD/ASSEMBLY_CUBE_Z-STAGE_mechanical_v2
says the parts can all be printed without support.
I printed the focus linear bearing flexure:
https://github.com/bionanoimaging/UC2-GIT/blob/master/CAD/ASSEMBLY_CUBE_Z-STAGE_mechanical_v2/STL/Assembly_Cube_Z-Focus_Linearbearing_1x1_v4_20_focus_inlet_linearflexure_v4_7.stl

and while the piece prints OK without support in the default orientation, the print quality is a bit low (the long bridges have lots of extra squigglies).  I don't want to add support on the bridging flexures, since it would be tough to remove.  Is there a way to put some internal supports in that can be easily removed to improve those? 

BTW I'm using a Prusa MK3S with PETG, but I can also do ABS and PLA.

**Comment by b286** [comment]
Hi, 

Thank you for your comment. We print this part with a 0,15 mm layer height with the Prusa MK3S, using various materials, and while there are some extra filament pieces where the printer prints 'in the air', this shouldn't have any effect on the performance of the part. 

If you feel like it'S needed, you can od support but removing it is not so easy and in my experience you risk breaking something that should stay in one piece.

**Comment by Kirk3gaard** [comment]
Hi 

I am surprised how well this printed even though there are quite a few horizontal pieces that have to be printed in the air. 

Best regards 
Rasmus 

![IMG_20210601_151221](https://user-images.githubusercontent.com/4373417/120436708-8dab2a80-c37f-11eb-8e31-5df8330000ac.jpg)
