### ISSUE TITLE
PSRAM ID read error - ESP32 while flashing LED matrix code

### ISSUE THREAD

**Issue by dhershm** [openUC2/UC2-GIT#79]
![Screenshot (55)](https://user-images.githubusercontent.com/81010688/148232830-a3984baa-72f2-4562-935f-06563014a91f.png)

Can't connect LED matrix with the ESP32 for the Incubator microscope. While checking the serial monitor, it shows the error in the picture given.

errors:
PSRAM ID read error: 0xffffffff

abort() was called at PC 0x40089631 on core 1

**Comment by beniroquai** [comment]
That is hard to debug. Did you enter the correct settings in the ESP32 Arduino IDE tool? Did you activate the PSRAM? 
Could you check just uploading the LED Matrix example from Adafruit?

**Comment by dhersm** [comment]
Yes ,  the settings are correct. As you suggested, we enabled PSRAM and the PSRAM error is solved but "abort() was called at PC 0x40086ed5 on core 1"  is still there. The motor is connected successfully via MQTT but the LED array is not.

**Comment by beniroquai** [comment]
I hope the error was resolved finally.
