### ISSUE TITLE
Motorised polarizer/filter rotating stage 

### ISSUE THREAD

**Issue by GiuseppeCiccone96** [openUC2/UC2-GIT#81]
Hi,

I think it would be really nice to integrate a motorised polariser/filter mount that is compatible with the uc2 framework and easily adaptable to other open-source microscopy projects such as the OpenFlexure.
A starting point can be [This paper](https://opg.optica.org/ao/fulltext.cfm?uri=ao-60-13-3764&id=450413), where they present a step-by-step guide to 3d print and assemble motorised rotating mounts for both transmission and reflection configurations!

**Comment by beniroquai** [comment]
Hey Giuseppe, 

thanks for pointing to this nice paper. I would really like to see this functionality in our system. Also it could help reducing speckles. 
I did a quick mockup using 3 ball bearings, a 3D printed timing belt and a 28byi stepper motor. What do you think?
[![Watch the video]()](https://user-images.githubusercontent.com/4345528/153837131-b368720a-3fac-4a7f-a531-f09a1175bc1a.mp4)

**Comment by GiuseppeCiccone96** [comment]
Hi Bene,

thanks so much for the quick try! 

I think it looks very promising - perhaps it could be integrated into the "APPLICATIONS" repository with instructions? 
Maybe one example could be an illuminator for polarization microscopy (I would like to try this out but we are currently moving labs and I don't have access to any equipment).

Thanks a lot for your support :) 

Giuseppe

**Comment by beniroquai** [comment]
[Tadah](https://github.com/openUC2/UC2-Motorized-Rotator). 
![uc2rot](https://user-images.githubusercontent.com/4345528/154210048-8f98e72e-679f-4150-a75a-6c6a2ba9ce1b.gif)

Feel free to comment :-)

**Comment by GiuseppeCiccone96** [comment]
Hi Bene, looks fantastic! 

I think the link may be broken though?

Giuseppe

**Comment by beniroquai** [comment]
Fixed. Sorry, for some reason it was set to private :)

**Comment by GiuseppeCiccone96** [comment]
not sure why but it still gives me error 404... :(

**Comment by beniroquai** [comment]
Hey, I'm very sorry. Now its really public!! ;-)
