### ISSUE TITLE
The Link is not working for the Eyepiece on the Simple Smartphone Page

### ISSUE THREAD

**Issue by Mzyetik** [openUC2/UC2-GIT#89]
The Link is not working for the Eyepiece on the following page
https://github.com/openUC2/UC2-GIT/tree/master/APPLICATIONS/APP_SIMPLE-Smartphone_Microscope/mechanical

the link which doesn't work is https://de.aliexpress.com/item/32965050204.html?spm=a2g0o.productlist.0.0.7aa657eeefLUfu&algo_pvid=cd60fca0-3fa5-4191-9ce9-303815e2afa7&algo_expid=cd60fca0-3fa5-4191-9ce9-303815e2afa7-1&btsid=76036b58-6717-4d1f-a4a0-c3d4bacd0450&ws_ab_test=searchweb0_0,searchweb201602_2,searchweb201603_52

**Comment by edabngl** [comment]
They are fixed.

**Comment by beniroquai** [comment]
Great! Thanks!
