### ISSUE TITLE
Neopixel voltage issues w/ ESP32

### ISSUE THREAD

**Issue by wbrett87** [openUC2/UC2-GIT#95]
I was having issues with using a neopixel array for lighting with an ESP32 (random behaviors like wrong pixels lighting up or wrong colors) here's what I found the solution to be:

The ESP32 outputs 3.2v logic, while the neopixel understands 5v logic. As I understand it, this means that often a 'high' signal (1 in binary) will be interpreted by the neopixel as a 'low'(0 in binary). This leads to unpredictable behavior. My solution was to put a 3.2v to 5v voltage shifter ([available here](https://www.adafruit.com/product/1787?gclid=Cj0KCQjwgO2XBhCaARIsANrW2X0hq6dTdA8NtRoWDUXhl61PgGD2RPxFdzIYT95VlkdHBjJqitz1LSMaAsx_EALw_wcB)) in between my ESP32 and neopixel. In addition I supplied the neopixel array with its own 5v dc power supply, as the ESP32 wasn't providing enough current to light up all of the pixels at once when plugged into a USB.

**Comment by beniroquai** [comment]
Hey, thanks for reporting. Indeed this may causes issues depending on the display you purchase. So far I feel very lucky - not sure why sometimes it works without any issues and sometimes it just doesn't.
